import { chromium } from "playwright";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { mkdirSync } from "fs";
const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "..", "qa-screenshots", "production-final");
mkdirSync(outDir, { recursive: true });
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: "reduce" });
const p = await ctx.newPage();
await p.goto("http://127.0.0.1:8123/index.html", { waitUntil: "networkidle" });
await p.waitForTimeout(1500);
await p.screenshot({ path: join(outDir, "r-hero-reduced.png") });
const total = await p.evaluate(() => document.documentElement.scrollHeight - window.innerHeight);
await p.evaluate((y)=>window.scrollTo(0,y), Math.round(total*0.27));
await p.waitForTimeout(500);
await p.screenshot({ path: join(outDir, "r-pain-reduced.png") });
await b.close();
console.log("reduced shots captured");
